spring:
  application:
    name: authorization-service
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authorization-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Christian12345%}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true

server:
  port: ${PORT:8082}

app:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
  security:
    jwt-secret: ${JWT_SECRET:9e1c6f5a3b4d8f0e2c7a1b9d6f4e8a3c7d2f5b1a9e6c3d8f0b4a7c2e5d9f1a6}
  identity-service:
    base-url: ${IDENTITY_SERVICE_BASE_URL:http://localhost:8081}
    user-validation-enabled: ${IDENTITY_USER_VALIDATION_ENABLED:true}
    service-token: ${IDENTITY_SERVICE_TOKEN:}
