INSERT INTO permissions (id_app, code, name, description)
SELECT apps.id, seed.code, seed.name, seed.description FROM apps CROSS JOIN (VALUES
('catalog.paises.view','Ver países','Consultar países'),('catalog.paises.create','Crear países','Crear países'),('catalog.paises.update','Editar países','Editar países'),('catalog.paises.delete','Eliminar países','Eliminar países'),
('catalog.estados.view','Ver estados','Consultar estados'),('catalog.estados.create','Crear estados','Crear estados'),('catalog.estados.update','Editar estados','Editar estados'),('catalog.estados.delete','Eliminar estados','Eliminar estados'),
('catalog.municipios.view','Ver municipios','Consultar municipios'),('catalog.municipios.create','Crear municipios','Crear municipios'),('catalog.municipios.update','Editar municipios','Editar municipios'),('catalog.municipios.delete','Eliminar municipios','Eliminar municipios'),
('catalog.ciudades.view','Ver ciudades','Consultar ciudades'),('catalog.ciudades.create','Crear ciudades','Crear ciudades'),('catalog.ciudades.update','Editar ciudades','Editar ciudades'),('catalog.ciudades.delete','Eliminar ciudades','Eliminar ciudades'),
('catalog.estados_civiles.view','Ver estados civiles','Consultar estados civiles'),('catalog.estados_civiles.create','Crear estados civiles','Crear estados civiles'),('catalog.estados_civiles.update','Editar estados civiles','Editar estados civiles'),('catalog.estados_civiles.delete','Eliminar estados civiles','Eliminar estados civiles'),
('catalog.monedas.view','Ver monedas','Consultar monedas'),('catalog.monedas.create','Crear monedas','Crear monedas'),('catalog.monedas.update','Editar monedas','Editar monedas'),('catalog.monedas.delete','Eliminar monedas','Eliminar monedas'),
('catalog.metodos_de_pago.view','Ver métodos de pago','Consultar métodos de pago'),('catalog.metodos_de_pago.create','Crear métodos de pago','Crear métodos de pago'),('catalog.metodos_de_pago.update','Editar métodos de pago','Editar métodos de pago'),('catalog.metodos_de_pago.delete','Eliminar métodos de pago','Eliminar métodos de pago'),
('catalog.estatus_de_pago.view','Ver estatus de pago','Consultar estatus de pago'),('catalog.estatus_de_pago.create','Crear estatus de pago','Crear estatus de pago'),('catalog.estatus_de_pago.update','Editar estatus de pago','Editar estatus de pago'),('catalog.estatus_de_pago.delete','Eliminar estatus de pago','Eliminar estatus de pago'),
('catalog.unidades.view','Ver unidades','Consultar unidades'),('catalog.unidades.create','Crear unidades','Crear unidades'),('catalog.unidades.update','Editar unidades','Editar unidades'),('catalog.unidades.delete','Eliminar unidades','Eliminar unidades')
) AS seed(code,name,description) WHERE apps.code='ADMIN_US' AND NOT EXISTS (SELECT 1 FROM permissions p WHERE p.id_app=apps.id AND p.code=seed.code);
